class Buffer:
	dimensions = object()
	def to_list(*argv):
		"""return the buffer as a list"""


GL_2D = int
GL_2_BYTES = int
GL_3D = int
GL_3D_COLOR = int
GL_3D_COLOR_TEXTURE = int
GL_3_BYTES = int
GL_4D_COLOR_TEXTURE = int
GL_4_BYTES = int
GL_ACCUM = int
GL_ACCUM_ALPHA_BITS = int
GL_ACCUM_BLUE_BITS = int
GL_ACCUM_BUFFER_BIT = int
GL_ACCUM_CLEAR_VALUE = int
GL_ACCUM_GREEN_BITS = int
GL_ACCUM_RED_BITS = int
GL_ACTIVE_ATTRIBUTES = int
GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = int
GL_ACTIVE_TEXTURE = int
GL_ACTIVE_UNIFORMS = int
GL_ACTIVE_UNIFORM_BLOCKS = int
GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH = int
GL_ACTIVE_UNIFORM_MAX_LENGTH = int
GL_ADD = int
GL_ADD_SIGNED = int
GL_ALIASED_LINE_WIDTH_RANGE = int
GL_ALIASED_POINT_SIZE_RANGE = int
GL_ALL_ATTRIB_BITS = int
GL_ALPHA = int
GL_ALPHA12 = int
GL_ALPHA16 = int
GL_ALPHA4 = int
GL_ALPHA8 = int
GL_ALPHA_BIAS = int
GL_ALPHA_BITS = int
GL_ALPHA_INTEGER = int
GL_ALPHA_SCALE = int
GL_ALPHA_TEST = int
GL_ALPHA_TEST_FUNC = int
GL_ALPHA_TEST_REF = int
GL_ALREADY_SIGNALED = int
GL_ALWAYS = int
GL_AMBIENT = int
GL_AMBIENT_AND_DIFFUSE = int
GL_AND = int
GL_AND_INVERTED = int
GL_AND_REVERSE = int
GL_ANY_SAMPLES_PASSED = int
GL_ARRAY_BUFFER = int
GL_ARRAY_BUFFER_BINDING = int
GL_ATTACHED_SHADERS = int
GL_ATTRIB_STACK_DEPTH = int
GL_AUTO_NORMAL = int
GL_AUX0 = int
GL_AUX1 = int
GL_AUX2 = int
GL_AUX3 = int
GL_AUX_BUFFERS = int
GL_BACK = int
GL_BACK_LEFT = int
GL_BACK_RIGHT = int
GL_BGR = int
GL_BGRA = int
GL_BGRA_INTEGER = int
GL_BGR_INTEGER = int
GL_BITMAP = int
GL_BITMAP_TOKEN = int
GL_BLEND = int
GL_BLEND_DST = int
GL_BLEND_DST_ALPHA = int
GL_BLEND_DST_RGB = int
GL_BLEND_EQUATION_ALPHA = int
GL_BLEND_EQUATION_RGB = int
GL_BLEND_SRC = int
GL_BLEND_SRC_ALPHA = int
GL_BLEND_SRC_RGB = int
GL_BLUE = int
GL_BLUE_BIAS = int
GL_BLUE_BITS = int
GL_BLUE_INTEGER = int
GL_BLUE_SCALE = int
GL_BOOL = int
GL_BOOL_VEC2 = int
GL_BOOL_VEC3 = int
GL_BOOL_VEC4 = int
GL_BUFFER_ACCESS = int
GL_BUFFER_ACCESS_FLAGS = int
GL_BUFFER_MAPPED = int
GL_BUFFER_MAP_LENGTH = int
GL_BUFFER_MAP_OFFSET = int
GL_BUFFER_MAP_POINTER = int
GL_BUFFER_SIZE = int
GL_BUFFER_USAGE = int
GL_BYTE = int
GL_C3F_V3F = int
GL_C4F_N3F_V3F = int
GL_C4UB_V2F = int
GL_C4UB_V3F = int
GL_CCW = int
GL_CLAMP = int
GL_CLAMP_FRAGMENT_COLOR = int
GL_CLAMP_READ_COLOR = int
GL_CLAMP_TO_BORDER = int
GL_CLAMP_TO_EDGE = int
GL_CLAMP_VERTEX_COLOR = int
GL_CLEAR = int
GL_CLIENT_ACTIVE_TEXTURE = int
GL_CLIENT_ALL_ATTRIB_BITS = int
GL_CLIENT_ATTRIB_STACK_DEPTH = int
GL_CLIENT_PIXEL_STORE_BIT = int
GL_CLIENT_VERTEX_ARRAY_BIT = int
GL_CLIP_DISTANCE0 = int
GL_CLIP_DISTANCE1 = int
GL_CLIP_DISTANCE2 = int
GL_CLIP_DISTANCE3 = int
GL_CLIP_DISTANCE4 = int
GL_CLIP_DISTANCE5 = int
GL_CLIP_PLANE0 = int
GL_CLIP_PLANE1 = int
GL_CLIP_PLANE2 = int
GL_CLIP_PLANE3 = int
GL_CLIP_PLANE4 = int
GL_CLIP_PLANE5 = int
GL_COEFF = int
GL_COLOR = int
GL_COLOR_ARRAY = int
GL_COLOR_ARRAY_BUFFER_BINDING = int
GL_COLOR_ARRAY_POINTER = int
GL_COLOR_ARRAY_SIZE = int
GL_COLOR_ARRAY_STRIDE = int
GL_COLOR_ARRAY_TYPE = int
GL_COLOR_ATTACHMENT0 = int
GL_COLOR_ATTACHMENT1 = int
GL_COLOR_ATTACHMENT10 = int
GL_COLOR_ATTACHMENT11 = int
GL_COLOR_ATTACHMENT12 = int
GL_COLOR_ATTACHMENT13 = int
GL_COLOR_ATTACHMENT14 = int
GL_COLOR_ATTACHMENT15 = int
GL_COLOR_ATTACHMENT2 = int
GL_COLOR_ATTACHMENT3 = int
GL_COLOR_ATTACHMENT4 = int
GL_COLOR_ATTACHMENT5 = int
GL_COLOR_ATTACHMENT6 = int
GL_COLOR_ATTACHMENT7 = int
GL_COLOR_ATTACHMENT8 = int
GL_COLOR_ATTACHMENT9 = int
GL_COLOR_BUFFER_BIT = int
GL_COLOR_CLEAR_VALUE = int
GL_COLOR_INDEX = int
GL_COLOR_INDEXES = int
GL_COLOR_LOGIC_OP = int
GL_COLOR_MATERIAL = int
GL_COLOR_MATERIAL_FACE = int
GL_COLOR_MATERIAL_PARAMETER = int
GL_COLOR_SUM = int
GL_COLOR_WRITEMASK = int
GL_COMBINE = int
GL_COMBINE_ALPHA = int
GL_COMBINE_RGB = int
GL_COMPARE_REF_TO_TEXTURE = int
GL_COMPARE_R_TO_TEXTURE = int
GL_COMPILE = int
GL_COMPILE_AND_EXECUTE = int
GL_COMPILE_STATUS = int
GL_COMPRESSED_ALPHA = int
GL_COMPRESSED_INTENSITY = int
GL_COMPRESSED_LUMINANCE = int
GL_COMPRESSED_LUMINANCE_ALPHA = int
GL_COMPRESSED_RED = int
GL_COMPRESSED_RED_RGTC1 = int
GL_COMPRESSED_RG = int
GL_COMPRESSED_RGB = int
GL_COMPRESSED_RGBA = int
GL_COMPRESSED_RG_RGTC2 = int
GL_COMPRESSED_SIGNED_RED_RGTC1 = int
GL_COMPRESSED_SIGNED_RG_RGTC2 = int
GL_COMPRESSED_SLUMINANCE = int
GL_COMPRESSED_SLUMINANCE_ALPHA = int
GL_COMPRESSED_SRGB = int
GL_COMPRESSED_SRGB_ALPHA = int
GL_COMPRESSED_TEXTURE_FORMATS = int
GL_CONDITION_SATISFIED = int
GL_CONSTANT = int
GL_CONSTANT_ALPHA = int
GL_CONSTANT_ATTENUATION = int
GL_CONSTANT_COLOR = int
GL_CONTEXT_COMPATIBILITY_PROFILE_BIT = int
GL_CONTEXT_CORE_PROFILE_BIT = int
GL_CONTEXT_FLAGS = int
GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT = int
GL_CONTEXT_PROFILE_MASK = int
GL_COORD_REPLACE = int
GL_COPY = int
GL_COPY_INVERTED = int
GL_COPY_PIXEL_TOKEN = int
GL_COPY_READ_BUFFER = int
GL_COPY_WRITE_BUFFER = int
GL_CULL_FACE = int
GL_CULL_FACE_MODE = int
GL_CURRENT_BIT = int
GL_CURRENT_COLOR = int
GL_CURRENT_FOG_COORD = int
GL_CURRENT_FOG_COORDINATE = int
GL_CURRENT_INDEX = int
GL_CURRENT_NORMAL = int
GL_CURRENT_PROGRAM = int
GL_CURRENT_QUERY = int
GL_CURRENT_RASTER_COLOR = int
GL_CURRENT_RASTER_DISTANCE = int
GL_CURRENT_RASTER_INDEX = int
GL_CURRENT_RASTER_POSITION = int
GL_CURRENT_RASTER_POSITION_VALID = int
GL_CURRENT_RASTER_SECONDARY_COLOR = int
GL_CURRENT_RASTER_TEXTURE_COORDS = int
GL_CURRENT_SECONDARY_COLOR = int
GL_CURRENT_TEXTURE_COORDS = int
GL_CURRENT_VERTEX_ATTRIB = int
GL_CW = int
GL_DECAL = int
GL_DECR = int
GL_DECR_WRAP = int
GL_DELETE_STATUS = int
GL_DEPTH = int
GL_DEPTH24_STENCIL8 = int
GL_DEPTH32F_STENCIL8 = int
GL_DEPTH_ATTACHMENT = int
GL_DEPTH_BIAS = int
GL_DEPTH_BITS = int
GL_DEPTH_BUFFER_BIT = int
GL_DEPTH_CLAMP = int
GL_DEPTH_CLEAR_VALUE = int
GL_DEPTH_COMPONENT = int
GL_DEPTH_COMPONENT16 = int
GL_DEPTH_COMPONENT24 = int
GL_DEPTH_COMPONENT32 = int
GL_DEPTH_COMPONENT32F = int
GL_DEPTH_FUNC = int
GL_DEPTH_RANGE = int
GL_DEPTH_SCALE = int
GL_DEPTH_STENCIL = int
GL_DEPTH_STENCIL_ATTACHMENT = int
GL_DEPTH_TEST = int
GL_DEPTH_TEXTURE_MODE = int
GL_DEPTH_WRITEMASK = int
GL_DIFFUSE = int
GL_DITHER = int
GL_DOMAIN = int
GL_DONT_CARE = int
GL_DOT3_RGB = int
GL_DOT3_RGBA = int
GL_DOUBLE = int
GL_DOUBLEBUFFER = int
GL_DRAW_BUFFER = int
GL_DRAW_BUFFER0 = int
GL_DRAW_BUFFER1 = int
GL_DRAW_BUFFER10 = int
GL_DRAW_BUFFER11 = int
GL_DRAW_BUFFER12 = int
GL_DRAW_BUFFER13 = int
GL_DRAW_BUFFER14 = int
GL_DRAW_BUFFER15 = int
GL_DRAW_BUFFER2 = int
GL_DRAW_BUFFER3 = int
GL_DRAW_BUFFER4 = int
GL_DRAW_BUFFER5 = int
GL_DRAW_BUFFER6 = int
GL_DRAW_BUFFER7 = int
GL_DRAW_BUFFER8 = int
GL_DRAW_BUFFER9 = int
GL_DRAW_FRAMEBUFFER = int
GL_DRAW_FRAMEBUFFER_BINDING = int
GL_DRAW_PIXEL_TOKEN = int
GL_DST_ALPHA = int
GL_DST_COLOR = int
GL_DYNAMIC_COPY = int
GL_DYNAMIC_DRAW = int
GL_DYNAMIC_READ = int
GL_EDGE_FLAG = int
GL_EDGE_FLAG_ARRAY = int
GL_EDGE_FLAG_ARRAY_BUFFER_BINDING = int
GL_EDGE_FLAG_ARRAY_POINTER = int
GL_EDGE_FLAG_ARRAY_STRIDE = int
GL_ELEMENT_ARRAY_BUFFER = int
GL_ELEMENT_ARRAY_BUFFER_BINDING = int
GL_EMISSION = int
GL_ENABLE_BIT = int
GL_EQUAL = int
GL_EQUIV = int
GL_EVAL_BIT = int
GL_EXP = int
GL_EXP2 = int
GL_EXTENSIONS = int
GL_EYE_LINEAR = int
GL_EYE_PLANE = int
GL_FALSE = int
GL_FASTEST = int
GL_FEEDBACK = int
GL_FEEDBACK_BUFFER_POINTER = int
GL_FEEDBACK_BUFFER_SIZE = int
GL_FEEDBACK_BUFFER_TYPE = int
GL_FILL = int
GL_FIRST_VERTEX_CONVENTION = int
GL_FIXED_ONLY = int
GL_FLAT = int
GL_FLOAT = int
GL_FLOAT_32_UNSIGNED_INT_24_8_REV = int
GL_FLOAT_MAT2 = int
GL_FLOAT_MAT2x3 = int
GL_FLOAT_MAT2x4 = int
GL_FLOAT_MAT3 = int
GL_FLOAT_MAT3x2 = int
GL_FLOAT_MAT3x4 = int
GL_FLOAT_MAT4 = int
GL_FLOAT_MAT4x2 = int
GL_FLOAT_MAT4x3 = int
GL_FLOAT_VEC2 = int
GL_FLOAT_VEC3 = int
GL_FLOAT_VEC4 = int
GL_FOG = int
GL_FOG_BIT = int
GL_FOG_COLOR = int
GL_FOG_COORD = int
GL_FOG_COORDINATE = int
GL_FOG_COORDINATE_ARRAY = int
GL_FOG_COORDINATE_ARRAY_BUFFER_BINDING = int
GL_FOG_COORDINATE_ARRAY_POINTER = int
GL_FOG_COORDINATE_ARRAY_STRIDE = int
GL_FOG_COORDINATE_ARRAY_TYPE = int
GL_FOG_COORDINATE_SOURCE = int
GL_FOG_COORD_ARRAY = int
GL_FOG_COORD_ARRAY_BUFFER_BINDING = int
GL_FOG_COORD_ARRAY_POINTER = int
GL_FOG_COORD_ARRAY_STRIDE = int
GL_FOG_COORD_ARRAY_TYPE = int
GL_FOG_COORD_SRC = int
GL_FOG_DENSITY = int
GL_FOG_END = int
GL_FOG_HINT = int
GL_FOG_INDEX = int
GL_FOG_MODE = int
GL_FOG_START = int
GL_FRAGMENT_DEPTH = int
GL_FRAGMENT_SHADER = int
GL_FRAGMENT_SHADER_DERIVATIVE_HINT = int
GL_FRAMEBUFFER = int
GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = int
GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = int
GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = int
GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = int
GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = int
GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = int
GL_FRAMEBUFFER_ATTACHMENT_LAYERED = int
GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = int
GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = int
GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE = int
GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = int
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = int
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = int
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = int
GL_FRAMEBUFFER_BINDING = int
GL_FRAMEBUFFER_COMPLETE = int
GL_FRAMEBUFFER_DEFAULT = int
GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = int
GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER = int
GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS = int
GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = int
GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = int
GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER = int
GL_FRAMEBUFFER_SRGB = int
GL_FRAMEBUFFER_UNDEFINED = int
GL_FRAMEBUFFER_UNSUPPORTED = int
GL_FRONT = int
GL_FRONT_AND_BACK = int
GL_FRONT_FACE = int
GL_FRONT_LEFT = int
GL_FRONT_RIGHT = int
GL_FUNC_ADD = int
GL_FUNC_REVERSE_SUBTRACT = int
GL_FUNC_SUBTRACT = int
GL_GENERATE_MIPMAP = int
GL_GENERATE_MIPMAP_HINT = int
GL_GEOMETRY_INPUT_TYPE = int
GL_GEOMETRY_OUTPUT_TYPE = int
GL_GEOMETRY_SHADER = int
GL_GEOMETRY_VERTICES_OUT = int
GL_GEQUAL = int
GL_GREATER = int
GL_GREEN = int
GL_GREEN_BIAS = int
GL_GREEN_BITS = int
GL_GREEN_INTEGER = int
GL_GREEN_SCALE = int
GL_HALF_FLOAT = int
GL_HINT_BIT = int
GL_INCR = int
GL_INCR_WRAP = int
GL_INDEX = int
GL_INDEX_ARRAY = int
GL_INDEX_ARRAY_BUFFER_BINDING = int
GL_INDEX_ARRAY_POINTER = int
GL_INDEX_ARRAY_STRIDE = int
GL_INDEX_ARRAY_TYPE = int
GL_INDEX_BITS = int
GL_INDEX_CLEAR_VALUE = int
GL_INDEX_LOGIC_OP = int
GL_INDEX_MODE = int
GL_INDEX_OFFSET = int
GL_INDEX_SHIFT = int
GL_INDEX_WRITEMASK = int
GL_INFO_LOG_LENGTH = int
GL_INT = int
GL_INTENSITY = int
GL_INTENSITY12 = int
GL_INTENSITY16 = int
GL_INTENSITY4 = int
GL_INTENSITY8 = int
GL_INTERLEAVED_ATTRIBS = int
GL_INTERPOLATE = int
GL_INT_2_10_10_10_REV = int
GL_INT_SAMPLER_1D = int
GL_INT_SAMPLER_1D_ARRAY = int
GL_INT_SAMPLER_2D = int
GL_INT_SAMPLER_2D_ARRAY = int
GL_INT_SAMPLER_2D_MULTISAMPLE = int
GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY = int
GL_INT_SAMPLER_2D_RECT = int
GL_INT_SAMPLER_3D = int
GL_INT_SAMPLER_BUFFER = int
GL_INT_SAMPLER_CUBE = int
GL_INT_VEC2 = int
GL_INT_VEC3 = int
GL_INT_VEC4 = int
GL_INVALID_ENUM = int
GL_INVALID_FRAMEBUFFER_OPERATION = int
GL_INVALID_INDEX = int
GL_INVALID_OPERATION = int
GL_INVALID_VALUE = int
GL_INVERT = int
GL_KEEP = int
GL_LAST_VERTEX_CONVENTION = int
GL_LEFT = int
GL_LEQUAL = int
GL_LESS = int
GL_LIGHT0 = int
GL_LIGHT1 = int
GL_LIGHT2 = int
GL_LIGHT3 = int
GL_LIGHT4 = int
GL_LIGHT5 = int
GL_LIGHT6 = int
GL_LIGHT7 = int
GL_LIGHTING = int
GL_LIGHTING_BIT = int
GL_LIGHT_MODEL_AMBIENT = int
GL_LIGHT_MODEL_COLOR_CONTROL = int
GL_LIGHT_MODEL_LOCAL_VIEWER = int
GL_LIGHT_MODEL_TWO_SIDE = int
GL_LINE = int
GL_LINEAR = int
GL_LINEAR_ATTENUATION = int
GL_LINEAR_MIPMAP_LINEAR = int
GL_LINEAR_MIPMAP_NEAREST = int
GL_LINES = int
GL_LINES_ADJACENCY = int
GL_LINE_BIT = int
GL_LINE_LOOP = int
GL_LINE_RESET_TOKEN = int
GL_LINE_SMOOTH = int
GL_LINE_SMOOTH_HINT = int
GL_LINE_STIPPLE = int
GL_LINE_STIPPLE_PATTERN = int
GL_LINE_STIPPLE_REPEAT = int
GL_LINE_STRIP = int
GL_LINE_STRIP_ADJACENCY = int
GL_LINE_TOKEN = int
GL_LINE_WIDTH = int
GL_LINE_WIDTH_GRANULARITY = int
GL_LINE_WIDTH_RANGE = int
GL_LINK_STATUS = int
GL_LIST_BASE = int
GL_LIST_BIT = int
GL_LIST_INDEX = int
GL_LIST_MODE = int
GL_LOAD = int
GL_LOGIC_OP = int
GL_LOGIC_OP_MODE = int
GL_LOWER_LEFT = int
GL_LUMINANCE = int
GL_LUMINANCE12 = int
GL_LUMINANCE12_ALPHA12 = int
GL_LUMINANCE12_ALPHA4 = int
GL_LUMINANCE16 = int
GL_LUMINANCE16_ALPHA16 = int
GL_LUMINANCE4 = int
GL_LUMINANCE4_ALPHA4 = int
GL_LUMINANCE6_ALPHA2 = int
GL_LUMINANCE8 = int
GL_LUMINANCE8_ALPHA8 = int
GL_LUMINANCE_ALPHA = int
GL_MAJOR_VERSION = int
GL_MAP1_COLOR_4 = int
GL_MAP1_GRID_DOMAIN = int
GL_MAP1_GRID_SEGMENTS = int
GL_MAP1_INDEX = int
GL_MAP1_NORMAL = int
GL_MAP1_TEXTURE_COORD_1 = int
GL_MAP1_TEXTURE_COORD_2 = int
GL_MAP1_TEXTURE_COORD_3 = int
GL_MAP1_TEXTURE_COORD_4 = int
GL_MAP1_VERTEX_3 = int
GL_MAP1_VERTEX_4 = int
GL_MAP2_COLOR_4 = int
GL_MAP2_GRID_DOMAIN = int
GL_MAP2_GRID_SEGMENTS = int
GL_MAP2_INDEX = int
GL_MAP2_NORMAL = int
GL_MAP2_TEXTURE_COORD_1 = int
GL_MAP2_TEXTURE_COORD_2 = int
GL_MAP2_TEXTURE_COORD_3 = int
GL_MAP2_TEXTURE_COORD_4 = int
GL_MAP2_VERTEX_3 = int
GL_MAP2_VERTEX_4 = int
GL_MAP_COLOR = int
GL_MAP_FLUSH_EXPLICIT_BIT = int
GL_MAP_INVALIDATE_BUFFER_BIT = int
GL_MAP_INVALIDATE_RANGE_BIT = int
GL_MAP_READ_BIT = int
GL_MAP_STENCIL = int
GL_MAP_UNSYNCHRONIZED_BIT = int
GL_MAP_WRITE_BIT = int
GL_MATRIX_MODE = int
GL_MAX = int
GL_MAX_3D_TEXTURE_SIZE = int
GL_MAX_ARRAY_TEXTURE_LAYERS = int
GL_MAX_ATTRIB_STACK_DEPTH = int
GL_MAX_CLIENT_ATTRIB_STACK_DEPTH = int
GL_MAX_CLIP_DISTANCES = int
GL_MAX_CLIP_PLANES = int
GL_MAX_COLOR_ATTACHMENTS = int
GL_MAX_COLOR_TEXTURE_SAMPLES = int
GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS = int
GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS = int
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = int
GL_MAX_COMBINED_UNIFORM_BLOCKS = int
GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS = int
GL_MAX_CUBE_MAP_TEXTURE_SIZE = int
GL_MAX_DEPTH_TEXTURE_SAMPLES = int
GL_MAX_DRAW_BUFFERS = int
GL_MAX_DUAL_SOURCE_DRAW_BUFFERS = int
GL_MAX_ELEMENTS_INDICES = int
GL_MAX_ELEMENTS_VERTICES = int
GL_MAX_EVAL_ORDER = int
GL_MAX_FRAGMENT_INPUT_COMPONENTS = int
GL_MAX_FRAGMENT_UNIFORM_BLOCKS = int
GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = int
GL_MAX_GEOMETRY_INPUT_COMPONENTS = int
GL_MAX_GEOMETRY_OUTPUT_COMPONENTS = int
GL_MAX_GEOMETRY_OUTPUT_VERTICES = int
GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS = int
GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS = int
GL_MAX_GEOMETRY_UNIFORM_BLOCKS = int
GL_MAX_GEOMETRY_UNIFORM_COMPONENTS = int
GL_MAX_INTEGER_SAMPLES = int
GL_MAX_LIGHTS = int
GL_MAX_LIST_NESTING = int
GL_MAX_MODELVIEW_STACK_DEPTH = int
GL_MAX_NAME_STACK_DEPTH = int
GL_MAX_PIXEL_MAP_TABLE = int
GL_MAX_PROGRAM_TEXEL_OFFSET = int
GL_MAX_PROJECTION_STACK_DEPTH = int
GL_MAX_RECTANGLE_TEXTURE_SIZE = int
GL_MAX_RENDERBUFFER_SIZE = int
GL_MAX_SAMPLES = int
GL_MAX_SAMPLE_MASK_WORDS = int
GL_MAX_SERVER_WAIT_TIMEOUT = int
GL_MAX_TEXTURE_BUFFER_SIZE = int
GL_MAX_TEXTURE_COORDS = int
GL_MAX_TEXTURE_IMAGE_UNITS = int
GL_MAX_TEXTURE_LOD_BIAS = int
GL_MAX_TEXTURE_SIZE = int
GL_MAX_TEXTURE_STACK_DEPTH = int
GL_MAX_TEXTURE_UNITS = int
GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = int
GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = int
GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = int
GL_MAX_UNIFORM_BLOCK_SIZE = int
GL_MAX_UNIFORM_BUFFER_BINDINGS = int
GL_MAX_VARYING_COMPONENTS = int
GL_MAX_VARYING_FLOATS = int
GL_MAX_VERTEX_ATTRIBS = int
GL_MAX_VERTEX_OUTPUT_COMPONENTS = int
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = int
GL_MAX_VERTEX_UNIFORM_BLOCKS = int
GL_MAX_VERTEX_UNIFORM_COMPONENTS = int
GL_MAX_VIEWPORT_DIMS = int
GL_MIN = int
GL_MINOR_VERSION = int
GL_MIN_PROGRAM_TEXEL_OFFSET = int
GL_MIRRORED_REPEAT = int
GL_MODELVIEW = int
GL_MODELVIEW_MATRIX = int
GL_MODELVIEW_STACK_DEPTH = int
GL_MODULATE = int
GL_MULT = int
GL_MULTISAMPLE = int
GL_MULTISAMPLE_BIT = int
GL_N3F_V3F = int
GL_NAME_STACK_DEPTH = int
GL_NAND = int
GL_NEAREST = int
GL_NEAREST_MIPMAP_LINEAR = int
GL_NEAREST_MIPMAP_NEAREST = int
GL_NEVER = int
GL_NICEST = int
GL_NONE = int
GL_NOOP = int
GL_NOR = int
GL_NORMALIZE = int
GL_NORMAL_ARRAY = int
GL_NORMAL_ARRAY_BUFFER_BINDING = int
GL_NORMAL_ARRAY_POINTER = int
GL_NORMAL_ARRAY_STRIDE = int
GL_NORMAL_ARRAY_TYPE = int
GL_NORMAL_MAP = int
GL_NOTEQUAL = int
GL_NO_ERROR = int
GL_NUM_COMPRESSED_TEXTURE_FORMATS = int
GL_NUM_EXTENSIONS = int
GL_OBJECT_LINEAR = int
GL_OBJECT_PLANE = int
GL_OBJECT_TYPE = int
GL_ONE = int
GL_ONE_MINUS_CONSTANT_ALPHA = int
GL_ONE_MINUS_CONSTANT_COLOR = int
GL_ONE_MINUS_DST_ALPHA = int
GL_ONE_MINUS_DST_COLOR = int
GL_ONE_MINUS_SRC1_ALPHA = int
GL_ONE_MINUS_SRC1_COLOR = int
GL_ONE_MINUS_SRC_ALPHA = int
GL_ONE_MINUS_SRC_COLOR = int
GL_OPERAND0_ALPHA = int
GL_OPERAND0_RGB = int
GL_OPERAND1_ALPHA = int
GL_OPERAND1_RGB = int
GL_OPERAND2_ALPHA = int
GL_OPERAND2_RGB = int
GL_OR = int
GL_ORDER = int
GL_OR_INVERTED = int
GL_OR_REVERSE = int
GL_OUT_OF_MEMORY = int
GL_PACK_ALIGNMENT = int
GL_PACK_IMAGE_HEIGHT = int
GL_PACK_LSB_FIRST = int
GL_PACK_ROW_LENGTH = int
GL_PACK_SKIP_IMAGES = int
GL_PACK_SKIP_PIXELS = int
GL_PACK_SKIP_ROWS = int
GL_PACK_SWAP_BYTES = int
GL_PASS_THROUGH_TOKEN = int
GL_PERSPECTIVE_CORRECTION_HINT = int
GL_PIXEL_MAP_A_TO_A = int
GL_PIXEL_MAP_A_TO_A_SIZE = int
GL_PIXEL_MAP_B_TO_B = int
GL_PIXEL_MAP_B_TO_B_SIZE = int
GL_PIXEL_MAP_G_TO_G = int
GL_PIXEL_MAP_G_TO_G_SIZE = int
GL_PIXEL_MAP_I_TO_A = int
GL_PIXEL_MAP_I_TO_A_SIZE = int
GL_PIXEL_MAP_I_TO_B = int
GL_PIXEL_MAP_I_TO_B_SIZE = int
GL_PIXEL_MAP_I_TO_G = int
GL_PIXEL_MAP_I_TO_G_SIZE = int
GL_PIXEL_MAP_I_TO_I = int
GL_PIXEL_MAP_I_TO_I_SIZE = int
GL_PIXEL_MAP_I_TO_R = int
GL_PIXEL_MAP_I_TO_R_SIZE = int
GL_PIXEL_MAP_R_TO_R = int
GL_PIXEL_MAP_R_TO_R_SIZE = int
GL_PIXEL_MAP_S_TO_S = int
GL_PIXEL_MAP_S_TO_S_SIZE = int
GL_PIXEL_MODE_BIT = int
GL_PIXEL_PACK_BUFFER = int
GL_PIXEL_PACK_BUFFER_BINDING = int
GL_PIXEL_UNPACK_BUFFER = int
GL_PIXEL_UNPACK_BUFFER_BINDING = int
GL_POINT = int
GL_POINTS = int
GL_POINT_BIT = int
GL_POINT_DISTANCE_ATTENUATION = int
GL_POINT_FADE_THRESHOLD_SIZE = int
GL_POINT_SIZE = int
GL_POINT_SIZE_GRANULARITY = int
GL_POINT_SIZE_MAX = int
GL_POINT_SIZE_MIN = int
GL_POINT_SIZE_RANGE = int
GL_POINT_SMOOTH = int
GL_POINT_SMOOTH_HINT = int
GL_POINT_SPRITE = int
GL_POINT_SPRITE_COORD_ORIGIN = int
GL_POINT_TOKEN = int
GL_POLYGON = int
GL_POLYGON_BIT = int
GL_POLYGON_MODE = int
GL_POLYGON_OFFSET_FACTOR = int
GL_POLYGON_OFFSET_FILL = int
GL_POLYGON_OFFSET_LINE = int
GL_POLYGON_OFFSET_POINT = int
GL_POLYGON_OFFSET_UNITS = int
GL_POLYGON_SMOOTH = int
GL_POLYGON_SMOOTH_HINT = int
GL_POLYGON_STIPPLE = int
GL_POLYGON_STIPPLE_BIT = int
GL_POLYGON_TOKEN = int
GL_POSITION = int
GL_PREVIOUS = int
GL_PRIMARY_COLOR = int
GL_PRIMITIVES_GENERATED = int
GL_PRIMITIVE_RESTART = int
GL_PRIMITIVE_RESTART_INDEX = int
GL_PROGRAM_POINT_SIZE = int
GL_PROJECTION = int
GL_PROJECTION_MATRIX = int
GL_PROJECTION_STACK_DEPTH = int
GL_PROVOKING_VERTEX = int
GL_PROXY_TEXTURE_1D = int
GL_PROXY_TEXTURE_1D_ARRAY = int
GL_PROXY_TEXTURE_2D = int
GL_PROXY_TEXTURE_2D_ARRAY = int
GL_PROXY_TEXTURE_2D_MULTISAMPLE = int
GL_PROXY_TEXTURE_2D_MULTISAMPLE_ARRAY = int
GL_PROXY_TEXTURE_3D = int
GL_PROXY_TEXTURE_CUBE_MAP = int
GL_PROXY_TEXTURE_RECTANGLE = int
GL_Q = int
GL_QUADRATIC_ATTENUATION = int
GL_QUADS = int
GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION = int
GL_QUAD_STRIP = int
GL_QUERY_BY_REGION_NO_WAIT = int
GL_QUERY_BY_REGION_WAIT = int
GL_QUERY_COUNTER_BITS = int
GL_QUERY_NO_WAIT = int
GL_QUERY_RESULT = int
GL_QUERY_RESULT_AVAILABLE = int
GL_QUERY_WAIT = int
GL_R = int
GL_R11F_G11F_B10F = int
GL_R16 = int
GL_R16F = int
GL_R16I = int
GL_R16UI = int
GL_R16_SNORM = int
GL_R32F = int
GL_R32I = int
GL_R32UI = int
GL_R3_G3_B2 = int
GL_R8 = int
GL_R8I = int
GL_R8UI = int
GL_R8_SNORM = int
GL_RASTERIZER_DISCARD = int
GL_READ_BUFFER = int
GL_READ_FRAMEBUFFER = int
GL_READ_FRAMEBUFFER_BINDING = int
GL_READ_ONLY = int
GL_READ_WRITE = int
GL_RED = int
GL_RED_BIAS = int
GL_RED_BITS = int
GL_RED_INTEGER = int
GL_RED_SCALE = int
GL_REFLECTION_MAP = int
GL_RENDER = int
GL_RENDERBUFFER = int
GL_RENDERBUFFER_ALPHA_SIZE = int
GL_RENDERBUFFER_BINDING = int
GL_RENDERBUFFER_BLUE_SIZE = int
GL_RENDERBUFFER_DEPTH_SIZE = int
GL_RENDERBUFFER_GREEN_SIZE = int
GL_RENDERBUFFER_HEIGHT = int
GL_RENDERBUFFER_INTERNAL_FORMAT = int
GL_RENDERBUFFER_RED_SIZE = int
GL_RENDERBUFFER_SAMPLES = int
GL_RENDERBUFFER_STENCIL_SIZE = int
GL_RENDERBUFFER_WIDTH = int
GL_RENDERER = int
GL_RENDER_MODE = int
GL_REPEAT = int
GL_REPLACE = int
GL_RESCALE_NORMAL = int
GL_RETURN = int
GL_RG = int
GL_RG16 = int
GL_RG16F = int
GL_RG16I = int
GL_RG16UI = int
GL_RG16_SNORM = int
GL_RG32F = int
GL_RG32I = int
GL_RG32UI = int
GL_RG8 = int
GL_RG8I = int
GL_RG8UI = int
GL_RG8_SNORM = int
GL_RGB = int
GL_RGB10 = int
GL_RGB10_A2 = int
GL_RGB10_A2UI = int
GL_RGB12 = int
GL_RGB16 = int
GL_RGB16F = int
GL_RGB16I = int
GL_RGB16UI = int
GL_RGB16_SNORM = int
GL_RGB32F = int
GL_RGB32I = int
GL_RGB32UI = int
GL_RGB4 = int
GL_RGB5 = int
GL_RGB5_A1 = int
GL_RGB8 = int
GL_RGB8I = int
GL_RGB8UI = int
GL_RGB8_SNORM = int
GL_RGB9_E5 = int
GL_RGBA = int
GL_RGBA12 = int
GL_RGBA16 = int
GL_RGBA16F = int
GL_RGBA16I = int
GL_RGBA16UI = int
GL_RGBA16_SNORM = int
GL_RGBA2 = int
GL_RGBA32F = int
GL_RGBA32I = int
GL_RGBA32UI = int
GL_RGBA4 = int
GL_RGBA8 = int
GL_RGBA8I = int
GL_RGBA8UI = int
GL_RGBA8_SNORM = int
GL_RGBA_INTEGER = int
GL_RGBA_MODE = int
GL_RGB_INTEGER = int
GL_RGB_SCALE = int
GL_RG_INTEGER = int
GL_RIGHT = int
GL_S = int
GL_SAMPLER_1D = int
GL_SAMPLER_1D_ARRAY = int
GL_SAMPLER_1D_ARRAY_SHADOW = int
GL_SAMPLER_1D_SHADOW = int
GL_SAMPLER_2D = int
GL_SAMPLER_2D_ARRAY = int
GL_SAMPLER_2D_ARRAY_SHADOW = int
GL_SAMPLER_2D_MULTISAMPLE = int
GL_SAMPLER_2D_MULTISAMPLE_ARRAY = int
GL_SAMPLER_2D_RECT = int
GL_SAMPLER_2D_RECT_SHADOW = int
GL_SAMPLER_2D_SHADOW = int
GL_SAMPLER_3D = int
GL_SAMPLER_BINDING = int
GL_SAMPLER_BUFFER = int
GL_SAMPLER_CUBE = int
GL_SAMPLER_CUBE_SHADOW = int
GL_SAMPLES = int
GL_SAMPLES_PASSED = int
GL_SAMPLE_ALPHA_TO_COVERAGE = int
GL_SAMPLE_ALPHA_TO_ONE = int
GL_SAMPLE_BUFFERS = int
GL_SAMPLE_COVERAGE = int
GL_SAMPLE_COVERAGE_INVERT = int
GL_SAMPLE_COVERAGE_VALUE = int
GL_SAMPLE_MASK = int
GL_SAMPLE_MASK_VALUE = int
GL_SAMPLE_POSITION = int
GL_SCISSOR_BIT = int
GL_SCISSOR_BOX = int
GL_SCISSOR_TEST = int
GL_SECONDARY_COLOR_ARRAY = int
GL_SECONDARY_COLOR_ARRAY_BUFFER_BINDING = int
GL_SECONDARY_COLOR_ARRAY_POINTER = int
GL_SECONDARY_COLOR_ARRAY_SIZE = int
GL_SECONDARY_COLOR_ARRAY_STRIDE = int
GL_SECONDARY_COLOR_ARRAY_TYPE = int
GL_SELECT = int
GL_SELECTION_BUFFER_POINTER = int
GL_SELECTION_BUFFER_SIZE = int
GL_SEPARATE_ATTRIBS = int
GL_SEPARATE_SPECULAR_COLOR = int
GL_SET = int
GL_SHADER_SOURCE_LENGTH = int
GL_SHADER_TYPE = int
GL_SHADE_MODEL = int
GL_SHADING_LANGUAGE_VERSION = int
GL_SHININESS = int
GL_SHORT = int
GL_SIGNALED = int
GL_SIGNED_NORMALIZED = int
GL_SINGLE_COLOR = int
GL_SLUMINANCE = int
GL_SLUMINANCE8 = int
GL_SLUMINANCE8_ALPHA8 = int
GL_SLUMINANCE_ALPHA = int
GL_SMOOTH = int
GL_SMOOTH_LINE_WIDTH_GRANULARITY = int
GL_SMOOTH_LINE_WIDTH_RANGE = int
GL_SMOOTH_POINT_SIZE_GRANULARITY = int
GL_SMOOTH_POINT_SIZE_RANGE = int
GL_SOURCE0_ALPHA = int
GL_SOURCE0_RGB = int
GL_SOURCE1_ALPHA = int
GL_SOURCE1_RGB = int
GL_SOURCE2_ALPHA = int
GL_SOURCE2_RGB = int
GL_SPECULAR = int
GL_SPHERE_MAP = int
GL_SPOT_CUTOFF = int
GL_SPOT_DIRECTION = int
GL_SPOT_EXPONENT = int
GL_SRC0_ALPHA = int
GL_SRC0_RGB = int
GL_SRC1_ALPHA = int
GL_SRC1_COLOR = int
GL_SRC1_RGB = int
GL_SRC2_ALPHA = int
GL_SRC2_RGB = int
GL_SRC_ALPHA = int
GL_SRC_ALPHA_SATURATE = int
GL_SRC_COLOR = int
GL_SRGB = int
GL_SRGB8 = int
GL_SRGB8_ALPHA8 = int
GL_SRGB_ALPHA = int
GL_STACK_OVERFLOW = int
GL_STACK_UNDERFLOW = int
GL_STATIC_COPY = int
GL_STATIC_DRAW = int
GL_STATIC_READ = int
GL_STENCIL = int
GL_STENCIL_ATTACHMENT = int
GL_STENCIL_BACK_FAIL = int
GL_STENCIL_BACK_FUNC = int
GL_STENCIL_BACK_PASS_DEPTH_FAIL = int
GL_STENCIL_BACK_PASS_DEPTH_PASS = int
GL_STENCIL_BACK_REF = int
GL_STENCIL_BACK_VALUE_MASK = int
GL_STENCIL_BACK_WRITEMASK = int
GL_STENCIL_BITS = int
GL_STENCIL_BUFFER_BIT = int
GL_STENCIL_CLEAR_VALUE = int
GL_STENCIL_FAIL = int
GL_STENCIL_FUNC = int
GL_STENCIL_INDEX = int
GL_STENCIL_INDEX1 = int
GL_STENCIL_INDEX16 = int
GL_STENCIL_INDEX4 = int
GL_STENCIL_INDEX8 = int
GL_STENCIL_PASS_DEPTH_FAIL = int
GL_STENCIL_PASS_DEPTH_PASS = int
GL_STENCIL_REF = int
GL_STENCIL_TEST = int
GL_STENCIL_VALUE_MASK = int
GL_STENCIL_WRITEMASK = int
GL_STEREO = int
GL_STREAM_COPY = int
GL_STREAM_DRAW = int
GL_STREAM_READ = int
GL_SUBPIXEL_BITS = int
GL_SUBTRACT = int
GL_SYNC_CONDITION = int
GL_SYNC_FENCE = int
GL_SYNC_FLAGS = int
GL_SYNC_FLUSH_COMMANDS_BIT = int
GL_SYNC_GPU_COMMANDS_COMPLETE = int
GL_SYNC_STATUS = int
GL_T = int
GL_T2F_C3F_V3F = int
GL_T2F_C4F_N3F_V3F = int
GL_T2F_C4UB_V3F = int
GL_T2F_N3F_V3F = int
GL_T2F_V3F = int
GL_T4F_C4F_N3F_V4F = int
GL_T4F_V4F = int
GL_TEXTURE = int
GL_TEXTURE0 = int
GL_TEXTURE1 = int
GL_TEXTURE10 = int
GL_TEXTURE11 = int
GL_TEXTURE12 = int
GL_TEXTURE13 = int
GL_TEXTURE14 = int
GL_TEXTURE15 = int
GL_TEXTURE16 = int
GL_TEXTURE17 = int
GL_TEXTURE18 = int
GL_TEXTURE19 = int
GL_TEXTURE2 = int
GL_TEXTURE20 = int
GL_TEXTURE21 = int
GL_TEXTURE22 = int
GL_TEXTURE23 = int
GL_TEXTURE24 = int
GL_TEXTURE25 = int
GL_TEXTURE26 = int
GL_TEXTURE27 = int
GL_TEXTURE28 = int
GL_TEXTURE29 = int
GL_TEXTURE3 = int
GL_TEXTURE30 = int
GL_TEXTURE31 = int
GL_TEXTURE4 = int
GL_TEXTURE5 = int
GL_TEXTURE6 = int
GL_TEXTURE7 = int
GL_TEXTURE8 = int
GL_TEXTURE9 = int
GL_TEXTURE_1D = int
GL_TEXTURE_1D_ARRAY = int
GL_TEXTURE_2D = int
GL_TEXTURE_2D_ARRAY = int
GL_TEXTURE_2D_MULTISAMPLE = int
GL_TEXTURE_2D_MULTISAMPLE_ARRAY = int
GL_TEXTURE_3D = int
GL_TEXTURE_ALPHA_SIZE = int
GL_TEXTURE_ALPHA_TYPE = int
GL_TEXTURE_BASE_LEVEL = int
GL_TEXTURE_BINDING_1D = int
GL_TEXTURE_BINDING_1D_ARRAY = int
GL_TEXTURE_BINDING_2D = int
GL_TEXTURE_BINDING_2D_ARRAY = int
GL_TEXTURE_BINDING_2D_MULTISAMPLE = int
GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY = int
GL_TEXTURE_BINDING_3D = int
GL_TEXTURE_BINDING_BUFFER = int
GL_TEXTURE_BINDING_CUBE_MAP = int
GL_TEXTURE_BINDING_RECTANGLE = int
GL_TEXTURE_BIT = int
GL_TEXTURE_BLUE_SIZE = int
GL_TEXTURE_BLUE_TYPE = int
GL_TEXTURE_BORDER = int
GL_TEXTURE_BORDER_COLOR = int
GL_TEXTURE_BUFFER = int
GL_TEXTURE_BUFFER_DATA_STORE_BINDING = int
GL_TEXTURE_COMPARE_FUNC = int
GL_TEXTURE_COMPARE_MODE = int
GL_TEXTURE_COMPONENTS = int
GL_TEXTURE_COMPRESSED = int
GL_TEXTURE_COMPRESSED_IMAGE_SIZE = int
GL_TEXTURE_COMPRESSION_HINT = int
GL_TEXTURE_COORD_ARRAY = int
GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING = int
GL_TEXTURE_COORD_ARRAY_POINTER = int
GL_TEXTURE_COORD_ARRAY_SIZE = int
GL_TEXTURE_COORD_ARRAY_STRIDE = int
GL_TEXTURE_COORD_ARRAY_TYPE = int
GL_TEXTURE_CUBE_MAP = int
GL_TEXTURE_CUBE_MAP_NEGATIVE_X = int
GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = int
GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = int
GL_TEXTURE_CUBE_MAP_POSITIVE_X = int
GL_TEXTURE_CUBE_MAP_POSITIVE_Y = int
GL_TEXTURE_CUBE_MAP_POSITIVE_Z = int
GL_TEXTURE_CUBE_MAP_SEAMLESS = int
GL_TEXTURE_DEPTH = int
GL_TEXTURE_DEPTH_SIZE = int
GL_TEXTURE_DEPTH_TYPE = int
GL_TEXTURE_ENV = int
GL_TEXTURE_ENV_COLOR = int
GL_TEXTURE_ENV_MODE = int
GL_TEXTURE_FILTER_CONTROL = int
GL_TEXTURE_FIXED_SAMPLE_LOCATIONS = int
GL_TEXTURE_GEN_MODE = int
GL_TEXTURE_GEN_Q = int
GL_TEXTURE_GEN_R = int
GL_TEXTURE_GEN_S = int
GL_TEXTURE_GEN_T = int
GL_TEXTURE_GREEN_SIZE = int
GL_TEXTURE_GREEN_TYPE = int
GL_TEXTURE_HEIGHT = int
GL_TEXTURE_INTENSITY_SIZE = int
GL_TEXTURE_INTENSITY_TYPE = int
GL_TEXTURE_INTERNAL_FORMAT = int
GL_TEXTURE_LOD_BIAS = int
GL_TEXTURE_LUMINANCE_SIZE = int
GL_TEXTURE_LUMINANCE_TYPE = int
GL_TEXTURE_MAG_FILTER = int
GL_TEXTURE_MATRIX = int
GL_TEXTURE_MAX_LEVEL = int
GL_TEXTURE_MAX_LOD = int
GL_TEXTURE_MIN_FILTER = int
GL_TEXTURE_MIN_LOD = int
GL_TEXTURE_PRIORITY = int
GL_TEXTURE_RECTANGLE = int
GL_TEXTURE_RED_SIZE = int
GL_TEXTURE_RED_TYPE = int
GL_TEXTURE_RESIDENT = int
GL_TEXTURE_SAMPLES = int
GL_TEXTURE_SHARED_SIZE = int
GL_TEXTURE_STACK_DEPTH = int
GL_TEXTURE_STENCIL_SIZE = int
GL_TEXTURE_SWIZZLE_A = int
GL_TEXTURE_SWIZZLE_B = int
GL_TEXTURE_SWIZZLE_G = int
GL_TEXTURE_SWIZZLE_R = int
GL_TEXTURE_SWIZZLE_RGBA = int
GL_TEXTURE_WIDTH = int
GL_TEXTURE_WRAP_R = int
GL_TEXTURE_WRAP_S = int
GL_TEXTURE_WRAP_T = int
GL_TIMEOUT_EXPIRED = int
GL_TIMEOUT_IGNORED = int
GL_TIMESTAMP = int
GL_TIME_ELAPSED = int
GL_TRANSFORM_BIT = int
GL_TRANSFORM_FEEDBACK_BUFFER = int
GL_TRANSFORM_FEEDBACK_BUFFER_BINDING = int
GL_TRANSFORM_FEEDBACK_BUFFER_MODE = int
GL_TRANSFORM_FEEDBACK_BUFFER_SIZE = int
GL_TRANSFORM_FEEDBACK_BUFFER_START = int
GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = int
GL_TRANSFORM_FEEDBACK_VARYINGS = int
GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH = int
GL_TRANSPOSE_COLOR_MATRIX = int
GL_TRANSPOSE_MODELVIEW_MATRIX = int
GL_TRANSPOSE_PROJECTION_MATRIX = int
GL_TRANSPOSE_TEXTURE_MATRIX = int
GL_TRIANGLES = int
GL_TRIANGLES_ADJACENCY = int
GL_TRIANGLE_FAN = int
GL_TRIANGLE_STRIP = int
GL_TRIANGLE_STRIP_ADJACENCY = int
GL_TRUE = int
GL_UNIFORM_ARRAY_STRIDE = int
GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS = int
GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES = int
GL_UNIFORM_BLOCK_BINDING = int
GL_UNIFORM_BLOCK_DATA_SIZE = int
GL_UNIFORM_BLOCK_INDEX = int
GL_UNIFORM_BLOCK_NAME_LENGTH = int
GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER = int
GL_UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER = int
GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER = int
GL_UNIFORM_BUFFER = int
GL_UNIFORM_BUFFER_BINDING = int
GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT = int
GL_UNIFORM_BUFFER_SIZE = int
GL_UNIFORM_BUFFER_START = int
GL_UNIFORM_IS_ROW_MAJOR = int
GL_UNIFORM_MATRIX_STRIDE = int
GL_UNIFORM_NAME_LENGTH = int
GL_UNIFORM_OFFSET = int
GL_UNIFORM_SIZE = int
GL_UNIFORM_TYPE = int
GL_UNPACK_ALIGNMENT = int
GL_UNPACK_IMAGE_HEIGHT = int
GL_UNPACK_LSB_FIRST = int
GL_UNPACK_ROW_LENGTH = int
GL_UNPACK_SKIP_IMAGES = int
GL_UNPACK_SKIP_PIXELS = int
GL_UNPACK_SKIP_ROWS = int
GL_UNPACK_SWAP_BYTES = int
GL_UNSIGNALED = int
GL_UNSIGNED_BYTE = int
GL_UNSIGNED_BYTE_2_3_3_REV = int
GL_UNSIGNED_BYTE_3_3_2 = int
GL_UNSIGNED_INT = int
GL_UNSIGNED_INT_10F_11F_11F_REV = int
GL_UNSIGNED_INT_10_10_10_2 = int
GL_UNSIGNED_INT_24_8 = int
GL_UNSIGNED_INT_2_10_10_10_REV = int
GL_UNSIGNED_INT_5_9_9_9_REV = int
GL_UNSIGNED_INT_8_8_8_8 = int
GL_UNSIGNED_INT_8_8_8_8_REV = int
GL_UNSIGNED_INT_SAMPLER_1D = int
GL_UNSIGNED_INT_SAMPLER_1D_ARRAY = int
GL_UNSIGNED_INT_SAMPLER_2D = int
GL_UNSIGNED_INT_SAMPLER_2D_ARRAY = int
GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE = int
GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY = int
GL_UNSIGNED_INT_SAMPLER_2D_RECT = int
GL_UNSIGNED_INT_SAMPLER_3D = int
GL_UNSIGNED_INT_SAMPLER_BUFFER = int
GL_UNSIGNED_INT_SAMPLER_CUBE = int
GL_UNSIGNED_INT_VEC2 = int
GL_UNSIGNED_INT_VEC3 = int
GL_UNSIGNED_INT_VEC4 = int
GL_UNSIGNED_NORMALIZED = int
GL_UNSIGNED_SHORT = int
GL_UNSIGNED_SHORT_1_5_5_5_REV = int
GL_UNSIGNED_SHORT_4_4_4_4 = int
GL_UNSIGNED_SHORT_4_4_4_4_REV = int
GL_UNSIGNED_SHORT_5_5_5_1 = int
GL_UNSIGNED_SHORT_5_6_5 = int
GL_UNSIGNED_SHORT_5_6_5_REV = int
GL_UPPER_LEFT = int
GL_V2F = int
GL_V3F = int
GL_VALIDATE_STATUS = int
GL_VENDOR = int
GL_VERSION = int
GL_VERTEX_ARRAY = int
GL_VERTEX_ARRAY_BINDING = int
GL_VERTEX_ARRAY_BUFFER_BINDING = int
GL_VERTEX_ARRAY_POINTER = int
GL_VERTEX_ARRAY_SIZE = int
GL_VERTEX_ARRAY_STRIDE = int
GL_VERTEX_ARRAY_TYPE = int
GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = int
GL_VERTEX_ATTRIB_ARRAY_DIVISOR = int
GL_VERTEX_ATTRIB_ARRAY_ENABLED = int
GL_VERTEX_ATTRIB_ARRAY_INTEGER = int
GL_VERTEX_ATTRIB_ARRAY_NORMALIZED = int
GL_VERTEX_ATTRIB_ARRAY_POINTER = int
GL_VERTEX_ATTRIB_ARRAY_SIZE = int
GL_VERTEX_ATTRIB_ARRAY_STRIDE = int
GL_VERTEX_ATTRIB_ARRAY_TYPE = int
GL_VERTEX_PROGRAM_POINT_SIZE = int
GL_VERTEX_PROGRAM_TWO_SIDE = int
GL_VERTEX_SHADER = int
GL_VIEWPORT = int
GL_VIEWPORT_BIT = int
GL_WAIT_FAILED = int
GL_WEIGHT_ARRAY_BUFFER_BINDING = int
GL_WRITE_ONLY = int
GL_XOR = int
GL_ZERO = int
GL_ZOOM_X = int
GL_ZOOM_Y = int
def glAccum(*argv):
	pass

def glActiveTexture(*argv):
	pass

def glAlphaFunc(*argv):
	pass

def glAreTexturesResident(*argv):
	pass

def glArrayElement(*argv):
	pass

def glAttachShader(*argv):
	pass

def glBegin(*argv):
	pass

def glBeginQuery(*argv):
	pass

def glBindAttribLocation(*argv):
	pass

def glBindBuffer(*argv):
	pass

def glBindBufferBase(*argv):
	pass

def glBindBufferRange(*argv):
	pass

def glBindTexture(*argv):
	pass

def glBindVertexArray(*argv):
	pass

def glBitmap(*argv):
	pass

def glBlendColor(*argv):
	pass

def glBlendEquation(*argv):
	pass

def glBlendEquationSeparate(*argv):
	pass

def glBlendFunc(*argv):
	pass

def glBufferData(*argv):
	pass

def glBufferSubData(*argv):
	pass

def glCallList(*argv):
	pass

def glCallLists(*argv):
	pass

def glClear(*argv):
	pass

def glClearAccum(*argv):
	pass

def glClearColor(*argv):
	pass

def glClearDepth(*argv):
	pass

def glClearIndex(*argv):
	pass

def glClearStencil(*argv):
	pass

def glClientActiveTexture(*argv):
	pass

def glClipPlane(*argv):
	pass

def glColor3b(*argv):
	pass

def glColor3bv(*argv):
	pass

def glColor3d(*argv):
	pass

def glColor3dv(*argv):
	pass

def glColor3f(*argv):
	pass

def glColor3fv(*argv):
	pass

def glColor3i(*argv):
	pass

def glColor3iv(*argv):
	pass

def glColor3s(*argv):
	pass

def glColor3sv(*argv):
	pass

def glColor3ub(*argv):
	pass

def glColor3ubv(*argv):
	pass

def glColor3ui(*argv):
	pass

def glColor3uiv(*argv):
	pass

def glColor3us(*argv):
	pass

def glColor3usv(*argv):
	pass

def glColor4b(*argv):
	pass

def glColor4bv(*argv):
	pass

def glColor4d(*argv):
	pass

def glColor4dv(*argv):
	pass

def glColor4f(*argv):
	pass

def glColor4fv(*argv):
	pass

def glColor4i(*argv):
	pass

def glColor4iv(*argv):
	pass

def glColor4s(*argv):
	pass

def glColor4sv(*argv):
	pass

def glColor4ub(*argv):
	pass

def glColor4ubv(*argv):
	pass

def glColor4ui(*argv):
	pass

def glColor4uiv(*argv):
	pass

def glColor4us(*argv):
	pass

def glColor4usv(*argv):
	pass

def glColorMask(*argv):
	pass

def glColorMaterial(*argv):
	pass

def glColorP3ui(*argv):
	pass

def glColorP3uiv(*argv):
	pass

def glColorP4ui(*argv):
	pass

def glColorP4uiv(*argv):
	pass

def glColorPointer(*argv):
	pass

def glCompileShader(*argv):
	pass

def glCompressedTexImage1D(*argv):
	pass

def glCompressedTexImage2D(*argv):
	pass

def glCompressedTexImage3D(*argv):
	pass

def glCompressedTexSubImage1D(*argv):
	pass

def glCompressedTexSubImage2D(*argv):
	pass

def glCompressedTexSubImage3D(*argv):
	pass

def glCopyPixels(*argv):
	pass

def glCopyTexImage1D(*argv):
	pass

def glCopyTexImage2D(*argv):
	pass

def glCopyTexSubImage1D(*argv):
	pass

def glCopyTexSubImage2D(*argv):
	pass

def glCopyTexSubImage3D(*argv):
	pass

def glCreateProgram(*argv):
	pass

def glCreateShader(*argv):
	pass

def glCullFace(*argv):
	pass

def glDeleteBuffers(*argv):
	pass

def glDeleteLists(*argv):
	pass

def glDeleteProgram(*argv):
	pass

def glDeleteQueries(*argv):
	pass

def glDeleteShader(*argv):
	pass

def glDeleteTextures(*argv):
	pass

def glDeleteVertexArrays(*argv):
	pass

def glDepthFunc(*argv):
	pass

def glDepthMask(*argv):
	pass

def glDepthRange(*argv):
	pass

def glDetachShader(*argv):
	pass

def glDisable(*argv):
	pass

def glDisableClientState(*argv):
	pass

def glDisableVertexAttribArray(*argv):
	pass

def glDrawArrays(*argv):
	pass

def glDrawBuffer(*argv):
	pass

def glDrawBuffers(*argv):
	pass

def glDrawElements(*argv):
	pass

def glDrawPixels(*argv):
	pass

def glDrawRangeElements(*argv):
	pass

def glEdgeFlag(*argv):
	pass

def glEdgeFlagPointer(*argv):
	pass

def glEdgeFlagv(*argv):
	pass

def glEnable(*argv):
	pass

def glEnableClientState(*argv):
	pass

def glEnableVertexAttribArray(*argv):
	pass

def glEnd(*argv):
	pass

def glEndList(*argv):
	pass

def glEndQuery(*argv):
	pass

def glEvalCoord1d(*argv):
	pass

def glEvalCoord1dv(*argv):
	pass

def glEvalCoord1f(*argv):
	pass

def glEvalCoord1fv(*argv):
	pass

def glEvalCoord2d(*argv):
	pass

def glEvalCoord2dv(*argv):
	pass

def glEvalCoord2f(*argv):
	pass

def glEvalCoord2fv(*argv):
	pass

def glEvalMesh1(*argv):
	pass

def glEvalMesh2(*argv):
	pass

def glEvalPoint1(*argv):
	pass

def glEvalPoint2(*argv):
	pass

def glFeedbackBuffer(*argv):
	pass

def glFinish(*argv):
	pass

def glFlush(*argv):
	pass

def glFogf(*argv):
	pass

def glFogfv(*argv):
	pass

def glFogi(*argv):
	pass

def glFogiv(*argv):
	pass

def glFramebufferTexture(*argv):
	pass

def glFrontFace(*argv):
	pass

def glFrustum(*argv):
	pass

def glGenBuffers(*argv):
	pass

def glGenLists(*argv):
	pass

def glGenQueries(*argv):
	pass

def glGenTextures(*argv):
	pass

def glGenVertexArrays(*argv):
	pass

def glGetActiveAttrib(*argv):
	pass

def glGetActiveUniform(*argv):
	pass

def glGetActiveUniformBlockName(*argv):
	pass

def glGetActiveUniformBlockiv(*argv):
	pass

def glGetActiveUniformName(*argv):
	pass

def glGetActiveUniformsiv(*argv):
	pass

def glGetAttachedShaders(*argv):
	pass

def glGetAttribLocation(*argv):
	pass

def glGetBooleanv(*argv):
	pass

def glGetBufferParameteri64v(*argv):
	pass

def glGetBufferParameteriv(*argv):
	pass

def glGetBufferPointerv(*argv):
	pass

def glGetBufferSubData(*argv):
	pass

def glGetClipPlane(*argv):
	pass

def glGetCompressedTexImage(*argv):
	pass

def glGetDoublev(*argv):
	pass

def glGetError(*argv):
	pass

def glGetFloatv(*argv):
	pass

def glGetInteger64i_v(*argv):
	pass

def glGetIntegeri_v(*argv):
	pass

def glGetIntegerv(*argv):
	pass

def glGetLightfv(*argv):
	pass

def glGetLightiv(*argv):
	pass

def glGetMapdv(*argv):
	pass

def glGetMapfv(*argv):
	pass

def glGetMapiv(*argv):
	pass

def glGetMaterialfv(*argv):
	pass

def glGetMaterialiv(*argv):
	pass

def glGetMultisamplefv(*argv):
	pass

def glGetPixelMapfv(*argv):
	pass

def glGetPixelMapuiv(*argv):
	pass

def glGetPixelMapusv(*argv):
	pass

def glGetPointerv(*argv):
	pass

def glGetPolygonStipple(*argv):
	pass

def glGetProgramInfoLog(*argv):
	pass

def glGetProgramiv(*argv):
	pass

def glGetQueryObjectiv(*argv):
	pass

def glGetQueryObjectuiv(*argv):
	pass

def glGetQueryiv(*argv):
	pass

def glGetShaderInfoLog(*argv):
	pass

def glGetShaderSource(*argv):
	pass

def glGetShaderiv(*argv):
	pass

def glGetString(*argv):
	pass

def glGetTexEnvfv(*argv):
	pass

def glGetTexEnviv(*argv):
	pass

def glGetTexGendv(*argv):
	pass

def glGetTexGenfv(*argv):
	pass

def glGetTexGeniv(*argv):
	pass

def glGetTexImage(*argv):
	pass

def glGetTexLevelParameterfv(*argv):
	pass

def glGetTexLevelParameteriv(*argv):
	pass

def glGetTexParameterfv(*argv):
	pass

def glGetTexParameteriv(*argv):
	pass

def glGetUniformBlockIndex(*argv):
	pass

def glGetUniformIndices(*argv):
	pass

def glGetUniformLocation(*argv):
	pass

def glGetUniformfv(*argv):
	pass

def glGetUniformiv(*argv):
	pass

def glGetVertexAttribPointerv(*argv):
	pass

def glGetVertexAttribdv(*argv):
	pass

def glGetVertexAttribfv(*argv):
	pass

def glGetVertexAttribiv(*argv):
	pass

def glHint(*argv):
	pass

def glIndexMask(*argv):
	pass

def glIndexPointer(*argv):
	pass

def glIndexd(*argv):
	pass

def glIndexdv(*argv):
	pass

def glIndexf(*argv):
	pass

def glIndexfv(*argv):
	pass

def glIndexi(*argv):
	pass

def glIndexiv(*argv):
	pass

def glIndexs(*argv):
	pass

def glIndexsv(*argv):
	pass

def glIndexub(*argv):
	pass

def glIndexubv(*argv):
	pass

def glInitNames(*argv):
	pass

def glInterleavedArrays(*argv):
	pass

def glIsBuffer(*argv):
	pass

def glIsEnabled(*argv):
	pass

def glIsList(*argv):
	pass

def glIsProgram(*argv):
	pass

def glIsQuery(*argv):
	pass

def glIsShader(*argv):
	pass

def glIsTexture(*argv):
	pass

def glIsVertexArray(*argv):
	pass

def glLightModelf(*argv):
	pass

def glLightModelfv(*argv):
	pass

def glLightModeli(*argv):
	pass

def glLightModeliv(*argv):
	pass

def glLightf(*argv):
	pass

def glLightfv(*argv):
	pass

def glLighti(*argv):
	pass

def glLightiv(*argv):
	pass

def glLineStipple(*argv):
	pass

def glLineWidth(*argv):
	pass

def glLinkProgram(*argv):
	pass

def glListBase(*argv):
	pass

def glLoadIdentity(*argv):
	pass

def glLoadMatrixd(*argv):
	pass

def glLoadMatrixf(*argv):
	pass

def glLoadName(*argv):
	pass

def glLoadTransposeMatrixd(*argv):
	pass

def glLoadTransposeMatrixf(*argv):
	pass

def glLogicOp(*argv):
	pass

def glMap1d(*argv):
	pass

def glMap1f(*argv):
	pass

def glMap2d(*argv):
	pass

def glMap2f(*argv):
	pass

def glMapBuffer(*argv):
	pass

def glMapGrid1d(*argv):
	pass

def glMapGrid1f(*argv):
	pass

def glMapGrid2d(*argv):
	pass

def glMapGrid2f(*argv):
	pass

def glMaterialf(*argv):
	pass

def glMaterialfv(*argv):
	pass

def glMateriali(*argv):
	pass

def glMaterialiv(*argv):
	pass

def glMatrixMode(*argv):
	pass

def glMultMatrixd(*argv):
	pass

def glMultMatrixf(*argv):
	pass

def glMultTransposeMatrixd(*argv):
	pass

def glMultTransposeMatrixf(*argv):
	pass

def glMultiTexCoord1d(*argv):
	pass

def glMultiTexCoord1dv(*argv):
	pass

def glMultiTexCoord1f(*argv):
	pass

def glMultiTexCoord1fv(*argv):
	pass

def glMultiTexCoord1i(*argv):
	pass

def glMultiTexCoord1iv(*argv):
	pass

def glMultiTexCoord1s(*argv):
	pass

def glMultiTexCoord1sv(*argv):
	pass

def glMultiTexCoord2d(*argv):
	pass

def glMultiTexCoord2dv(*argv):
	pass

def glMultiTexCoord2f(*argv):
	pass

def glMultiTexCoord2fv(*argv):
	pass

def glMultiTexCoord2i(*argv):
	pass

def glMultiTexCoord2iv(*argv):
	pass

def glMultiTexCoord2s(*argv):
	pass

def glMultiTexCoord2sv(*argv):
	pass

def glMultiTexCoord3d(*argv):
	pass

def glMultiTexCoord3dv(*argv):
	pass

def glMultiTexCoord3f(*argv):
	pass

def glMultiTexCoord3fv(*argv):
	pass

def glMultiTexCoord3i(*argv):
	pass

def glMultiTexCoord3iv(*argv):
	pass

def glMultiTexCoord3s(*argv):
	pass

def glMultiTexCoord3sv(*argv):
	pass

def glMultiTexCoord4d(*argv):
	pass

def glMultiTexCoord4dv(*argv):
	pass

def glMultiTexCoord4f(*argv):
	pass

def glMultiTexCoord4fv(*argv):
	pass

def glMultiTexCoord4i(*argv):
	pass

def glMultiTexCoord4iv(*argv):
	pass

def glMultiTexCoord4s(*argv):
	pass

def glMultiTexCoord4sv(*argv):
	pass

def glMultiTexCoordP1ui(*argv):
	pass

def glMultiTexCoordP1uiv(*argv):
	pass

def glMultiTexCoordP2ui(*argv):
	pass

def glMultiTexCoordP2uiv(*argv):
	pass

def glMultiTexCoordP3ui(*argv):
	pass

def glMultiTexCoordP3uiv(*argv):
	pass

def glMultiTexCoordP4ui(*argv):
	pass

def glMultiTexCoordP4uiv(*argv):
	pass

def glNewList(*argv):
	pass

def glNormal3b(*argv):
	pass

def glNormal3bv(*argv):
	pass

def glNormal3d(*argv):
	pass

def glNormal3dv(*argv):
	pass

def glNormal3f(*argv):
	pass

def glNormal3fv(*argv):
	pass

def glNormal3i(*argv):
	pass

def glNormal3iv(*argv):
	pass

def glNormal3s(*argv):
	pass

def glNormal3sv(*argv):
	pass

def glNormalP3ui(*argv):
	pass

def glNormalP3uiv(*argv):
	pass

def glNormalPointer(*argv):
	pass

def glOrtho(*argv):
	pass

def glPassThrough(*argv):
	pass

def glPixelMapfv(*argv):
	pass

def glPixelMapuiv(*argv):
	pass

def glPixelMapusv(*argv):
	pass

def glPixelStoref(*argv):
	pass

def glPixelStorei(*argv):
	pass

def glPixelTransferf(*argv):
	pass

def glPixelTransferi(*argv):
	pass

def glPixelZoom(*argv):
	pass

def glPointSize(*argv):
	pass

def glPolygonMode(*argv):
	pass

def glPolygonOffset(*argv):
	pass

def glPolygonStipple(*argv):
	pass

def glPopAttrib(*argv):
	pass

def glPopClientAttrib(*argv):
	pass

def glPopMatrix(*argv):
	pass

def glPopName(*argv):
	pass

def glPrioritizeTextures(*argv):
	pass

def glPushAttrib(*argv):
	pass

def glPushClientAttrib(*argv):
	pass

def glPushMatrix(*argv):
	pass

def glPushName(*argv):
	pass

def glRasterPos2d(*argv):
	pass

def glRasterPos2dv(*argv):
	pass

def glRasterPos2f(*argv):
	pass

def glRasterPos2fv(*argv):
	pass

def glRasterPos2i(*argv):
	pass

def glRasterPos2iv(*argv):
	pass

def glRasterPos2s(*argv):
	pass

def glRasterPos2sv(*argv):
	pass

def glRasterPos3d(*argv):
	pass

def glRasterPos3dv(*argv):
	pass

def glRasterPos3f(*argv):
	pass

def glRasterPos3fv(*argv):
	pass

def glRasterPos3i(*argv):
	pass

def glRasterPos3iv(*argv):
	pass

def glRasterPos3s(*argv):
	pass

def glRasterPos3sv(*argv):
	pass

def glRasterPos4d(*argv):
	pass

def glRasterPos4dv(*argv):
	pass

def glRasterPos4f(*argv):
	pass

def glRasterPos4fv(*argv):
	pass

def glRasterPos4i(*argv):
	pass

def glRasterPos4iv(*argv):
	pass

def glRasterPos4s(*argv):
	pass

def glRasterPos4sv(*argv):
	pass

def glReadBuffer(*argv):
	pass

def glReadPixels(*argv):
	pass

def glRectd(*argv):
	pass

def glRectdv(*argv):
	pass

def glRectf(*argv):
	pass

def glRectfv(*argv):
	pass

def glRecti(*argv):
	pass

def glRectiv(*argv):
	pass

def glRects(*argv):
	pass

def glRectsv(*argv):
	pass

def glRenderMode(*argv):
	pass

def glRotated(*argv):
	pass

def glRotatef(*argv):
	pass

def glSampleCoverage(*argv):
	pass

def glSampleMaski(*argv):
	pass

def glScaled(*argv):
	pass

def glScalef(*argv):
	pass

def glScissor(*argv):
	pass

def glSecondaryColorP3ui(*argv):
	pass

def glSecondaryColorP3uiv(*argv):
	pass

def glSelectBuffer(*argv):
	pass

def glShadeModel(*argv):
	pass

def glShaderSource(*argv):
	pass

def glStencilFunc(*argv):
	pass

def glStencilFuncSeparate(*argv):
	pass

def glStencilMask(*argv):
	pass

def glStencilMaskSeparate(*argv):
	pass

def glStencilOp(*argv):
	pass

def glStencilOpSeparate(*argv):
	pass

def glTexCoord1d(*argv):
	pass

def glTexCoord1dv(*argv):
	pass

def glTexCoord1f(*argv):
	pass

def glTexCoord1fv(*argv):
	pass

def glTexCoord1i(*argv):
	pass

def glTexCoord1iv(*argv):
	pass

def glTexCoord1s(*argv):
	pass

def glTexCoord1sv(*argv):
	pass

def glTexCoord2d(*argv):
	pass

def glTexCoord2dv(*argv):
	pass

def glTexCoord2f(*argv):
	pass

def glTexCoord2fv(*argv):
	pass

def glTexCoord2i(*argv):
	pass

def glTexCoord2iv(*argv):
	pass

def glTexCoord2s(*argv):
	pass

def glTexCoord2sv(*argv):
	pass

def glTexCoord3d(*argv):
	pass

def glTexCoord3dv(*argv):
	pass

def glTexCoord3f(*argv):
	pass

def glTexCoord3fv(*argv):
	pass

def glTexCoord3i(*argv):
	pass

def glTexCoord3iv(*argv):
	pass

def glTexCoord3s(*argv):
	pass

def glTexCoord3sv(*argv):
	pass

def glTexCoord4d(*argv):
	pass

def glTexCoord4dv(*argv):
	pass

def glTexCoord4f(*argv):
	pass

def glTexCoord4fv(*argv):
	pass

def glTexCoord4i(*argv):
	pass

def glTexCoord4iv(*argv):
	pass

def glTexCoord4s(*argv):
	pass

def glTexCoord4sv(*argv):
	pass

def glTexCoordP1ui(*argv):
	pass

def glTexCoordP1uiv(*argv):
	pass

def glTexCoordP2ui(*argv):
	pass

def glTexCoordP2uiv(*argv):
	pass

def glTexCoordP3ui(*argv):
	pass

def glTexCoordP3uiv(*argv):
	pass

def glTexCoordP4ui(*argv):
	pass

def glTexCoordP4uiv(*argv):
	pass

def glTexCoordPointer(*argv):
	pass

def glTexEnvf(*argv):
	pass

def glTexEnvfv(*argv):
	pass

def glTexEnvi(*argv):
	pass

def glTexEnviv(*argv):
	pass

def glTexGend(*argv):
	pass

def glTexGendv(*argv):
	pass

def glTexGenf(*argv):
	pass

def glTexGenfv(*argv):
	pass

def glTexGeni(*argv):
	pass

def glTexGeniv(*argv):
	pass

def glTexImage1D(*argv):
	pass

def glTexImage2D(*argv):
	pass

def glTexImage2DMultisample(*argv):
	pass

def glTexImage3D(*argv):
	pass

def glTexImage3DMultisample(*argv):
	pass

def glTexParameterf(*argv):
	pass

def glTexParameterfv(*argv):
	pass

def glTexParameteri(*argv):
	pass

def glTexParameteriv(*argv):
	pass

def glTexSubImage1D(*argv):
	pass

def glTexSubImage2D(*argv):
	pass

def glTexSubImage3D(*argv):
	pass

def glTranslated(*argv):
	pass

def glTranslatef(*argv):
	pass

def glUniform1f(*argv):
	pass

def glUniform1fv(*argv):
	pass

def glUniform1i(*argv):
	pass

def glUniform1iv(*argv):
	pass

def glUniform2f(*argv):
	pass

def glUniform2fv(*argv):
	pass

def glUniform2i(*argv):
	pass

def glUniform2iv(*argv):
	pass

def glUniform3f(*argv):
	pass

def glUniform3fv(*argv):
	pass

def glUniform3i(*argv):
	pass

def glUniform3iv(*argv):
	pass

def glUniform4f(*argv):
	pass

def glUniform4fv(*argv):
	pass

def glUniform4i(*argv):
	pass

def glUniform4iv(*argv):
	pass

def glUniformBlockBinding(*argv):
	pass

def glUniformMatrix2fv(*argv):
	pass

def glUniformMatrix2x3fv(*argv):
	pass

def glUniformMatrix2x4fv(*argv):
	pass

def glUniformMatrix3fv(*argv):
	pass

def glUniformMatrix3x2fv(*argv):
	pass

def glUniformMatrix3x4fv(*argv):
	pass

def glUniformMatrix4fv(*argv):
	pass

def glUniformMatrix4x2fv(*argv):
	pass

def glUniformMatrix4x3fv(*argv):
	pass

def glUnmapBuffer(*argv):
	pass

def glUseProgram(*argv):
	pass

def glValidateProgram(*argv):
	pass

def glVertex2d(*argv):
	pass

def glVertex2dv(*argv):
	pass

def glVertex2f(*argv):
	pass

def glVertex2fv(*argv):
	pass

def glVertex2i(*argv):
	pass

def glVertex2iv(*argv):
	pass

def glVertex2s(*argv):
	pass

def glVertex2sv(*argv):
	pass

def glVertex3d(*argv):
	pass

def glVertex3dv(*argv):
	pass

def glVertex3f(*argv):
	pass

def glVertex3fv(*argv):
	pass

def glVertex3i(*argv):
	pass

def glVertex3iv(*argv):
	pass

def glVertex3s(*argv):
	pass

def glVertex3sv(*argv):
	pass

def glVertex4d(*argv):
	pass

def glVertex4dv(*argv):
	pass

def glVertex4f(*argv):
	pass

def glVertex4fv(*argv):
	pass

def glVertex4i(*argv):
	pass

def glVertex4iv(*argv):
	pass

def glVertex4s(*argv):
	pass

def glVertex4sv(*argv):
	pass

def glVertexAttrib1d(*argv):
	pass

def glVertexAttrib1dv(*argv):
	pass

def glVertexAttrib1f(*argv):
	pass

def glVertexAttrib1fv(*argv):
	pass

def glVertexAttrib1s(*argv):
	pass

def glVertexAttrib1sv(*argv):
	pass

def glVertexAttrib2d(*argv):
	pass

def glVertexAttrib2dv(*argv):
	pass

def glVertexAttrib2f(*argv):
	pass

def glVertexAttrib2fv(*argv):
	pass

def glVertexAttrib2s(*argv):
	pass

def glVertexAttrib2sv(*argv):
	pass

def glVertexAttrib3d(*argv):
	pass

def glVertexAttrib3dv(*argv):
	pass

def glVertexAttrib3f(*argv):
	pass

def glVertexAttrib3fv(*argv):
	pass

def glVertexAttrib3s(*argv):
	pass

def glVertexAttrib3sv(*argv):
	pass

def glVertexAttrib4Nbv(*argv):
	pass

def glVertexAttrib4Niv(*argv):
	pass

def glVertexAttrib4Nsv(*argv):
	pass

def glVertexAttrib4Nub(*argv):
	pass

def glVertexAttrib4Nubv(*argv):
	pass

def glVertexAttrib4Nuiv(*argv):
	pass

def glVertexAttrib4Nusv(*argv):
	pass

def glVertexAttrib4bv(*argv):
	pass

def glVertexAttrib4d(*argv):
	pass

def glVertexAttrib4dv(*argv):
	pass

def glVertexAttrib4f(*argv):
	pass

def glVertexAttrib4fv(*argv):
	pass

def glVertexAttrib4iv(*argv):
	pass

def glVertexAttrib4s(*argv):
	pass

def glVertexAttrib4sv(*argv):
	pass

def glVertexAttrib4ubv(*argv):
	pass

def glVertexAttrib4uiv(*argv):
	pass

def glVertexAttrib4usv(*argv):
	pass

def glVertexAttribPointer(*argv):
	pass

def glVertexP2ui(*argv):
	pass

def glVertexP2uiv(*argv):
	pass

def glVertexP3ui(*argv):
	pass

def glVertexP3uiv(*argv):
	pass

def glVertexP4ui(*argv):
	pass

def glVertexP4uiv(*argv):
	pass

def glVertexPointer(*argv):
	pass

def glViewport(*argv):
	pass

def gluLookAt(*argv):
	pass

def gluOrtho2D(*argv):
	pass

def gluPerspective(*argv):
	pass

def gluPickMatrix(*argv):
	pass

def gluProject(*argv):
	pass

def gluUnProject(*argv):
	pass


